version: '3.8'

services:
  youtube-summary:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
        VITE_SUPADATA_API_KEY: ${VITE_SUPADATA_API_KEY}
    ports:
      - "4500:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: youtube-summary-app
    volumes:
      # Mount nginx config if you want to customize it
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Optional: Add a reverse proxy for multiple services
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - youtube-summary
  #   restart: unless-stopped

networks:
  default:
    driver: bridge