version: '3.8'

services:
  youtube-summary:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
        VITE_SUPADATA_API_KEY: ${VITE_SUPADATA_API_KEY}
    ports:
      - "${PORT:-4500}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: youtube-summary-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge